site_name: IMMORTAL BROTHERHOOD Documentation
site_url: https://Tunetown187.github.io/IMMORTAL_BROTHERHOOD/
repo_url: https://github.com/Tunetown187/IMMORTAL_BROTHERHOOD
edit_uri: edit/main/docs/

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - search.suggest
    - search.highlight
  palette:
    scheme: slate
    primary: deep purple
    accent: purple

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          setup_commands:
            - import sys
            - sys.path.append(".")
          selection:
            members: true
          rendering:
            show_source: true

nav:
  - Home: index.md
  - Revenue Streams:
    - Crypto Operations: crypto.md
    - AI Music & Royalties: music.md
    - Affiliate Marketing: affiliate.md
    - E-commerce & Dropshipping: ecommerce.md
    - Faceless YouTube: youtube.md
  - Technology:
    - AI Agents: ai-agents.md
    - Website Development: websites.md
  - Resources:
    - Resource Center: resources.md
  - API Reference: api.md

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.emoji
  - admonition
  - meta
