<<<<<<< HEAD
site_name: IMMORTAL BROTHERHOOD Documentation
site_url: https://Tunetown187.github.io/IMMORTAL_BROTHERHOOD/
repo_url: https://github.com/Tunetown187/IMMORTAL_BROTHERHOOD
edit_uri: edit/main/docs/

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - search.suggest
    - search.highlight
  palette:
    scheme: slate
    primary: deep purple
    accent: purple

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          setup_commands:
            - import sys
            - sys.path.append(".")
          selection:
            members: true
          rendering:
            show_source: true

nav:
  - Home: index.md
  - Revenue Streams:
    - Crypto Operations: crypto.md
    - AI Music & Royalties: music.md
    - Affiliate Marketing: affiliate.md
    - E-commerce & Dropshipping: ecommerce.md
    - Faceless YouTube: youtube.md
  - Technology:
    - AI Agents: ai-agents.md
    - Website Development: websites.md
  - Resources:
    - Resource Center: resources.md
  - API Reference: api.md

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.emoji
  - admonition
  - meta
=======
site_name: Agency Swarm
site_author: Arsenii Shatokhin
site_description: A an open source agent orchestration framework based on the latest OpenAI Assistants API.
theme:
  features:
    - search.suggest
    - search.highlight
    - search.share
    - navigation.expand
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.prune
#    - navigation.sections
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - content.code.select
    - content.code.copy
  name: material
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: black
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: amber
      accent: yellow
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
nav:
  - Introduction: "index.md"
  - Quick Start: "quick_start.md"
  - Advanced Usage:
    - Advanced Tools: "advanced-usage/tools.md"
    - Agents: "advanced-usage/agents.md"
    - Agencies: "advanced-usage/agencies.md"
    - Azure OpenAI: "advanced-usage/azure-openai.md"
  - Deployment to Production: "deployment.md"
  - API Reference: "api.md"
  - Contributing: "contributing.md"
  - Examples: "examples.md"
plugins:
  - mkdocs-jupyter:
      ignore_h1_titles: true
      execute: false
  - search
  - mkdocstrings
markdown_extensions:
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
extra:
  generator: false
  social:
    - icon: fontawesome/brands/mastodon
      link: https://www.vrsen.ai/
    - icon: fontawesome/brands/github
      link: https://github.com/VRSEN/agency-swarm
    - icon: fontawesome/brands/x-twitter
      link: https://twitter.com/__vrsen__
>>>>>>> db212065e73763a8569ee9943d5941533a7f5fc6
