site_name: IMMORTAL BROTHERHOOD Documentation
site_url: https://Tunetown187.github.io/IMMORTAL_BROTHERHOOD/
repo_url: https://github.com/Tunetown187/IMMORTAL_BROTHERHOOD
edit_uri: edit/main/docs/

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - search.suggest
    - search.highlight
  palette:
    primary: indigo
    accent: indigo

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          setup_commands:
            - import sys
            - sys.path.append(".")
          selection:
            members: true
          rendering:
            show_source: true

nav:
  - Home: index.md
  - API Reference: api.md

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
