[theme]
primaryColor = "#FF4B4B"
backgroundColor = "#0E1117"
secondaryBackgroundColor = "#262730"
textColor = "#FAFAFA"
font = "sans serif"

[server]
maxUploadSize = 200
enableXsrfProtection = true
enableCORS = false
maxMessageSize = 200
enableWebsocketCompression = true
port = 8501
address = "0.0.0.0"
headless = true

[browser]
gatherUsageStats = false
serverAddress = "0.0.0.0"
serverPort = 8501

[runner]
magicEnabled = true
fastReruns = true
enforceSerializableSessionState = false
postScriptGC = true

[client]
showErrorDetails = false
toolbarMode = "minimal"
caching = true

[logger]
level = "info"
messageFormat = "%(asctime)s %(levelname)s %(message)s"

[global]
developmentMode = false
disableWatchdogWarning = true
suppressDeprecationWarnings = true

[mapbox]
token = ""
