# Blockchain API Keys
[ethereum]
rpc_url = "https://mainnet.infura.io/v3/227d72486e8a4af8bd340cef3fe204c6"
private_key = "0x7ae94d8a2aafc5d06c4bf82d70f4f042654aeff8db755608def3546235d90412"

[polygon]
rpc_url = "https://polygon-rpc.com"
private_key = "0x7ae94d8a2aafc5d06c4bf82d70f4f042654aeff8db755608def3546235d90412"

[base]
rpc_url = "https://mainnet.base.org"
private_key = "0x7ae94d8a2aafc5d06c4bf82d70f4f042654aeff8db755608def3546235d90412"

[bitcoin]
private_key = "L3C9zKDU5TFBAfGmwHQbJbWRTScn31pKaVLcRZpQENgcUoKXBJCF"
rpc_url = "https://btc.getblock.io/mainnet/"

[solana]
rpc_url = "https://api.mainnet-beta.solana.com"
private_key = "2FFhe61Db5oHyYQ5yQ6QN5mnsUMpSwJ8kNQPvrC23L18o2uNkCR4V3y7QzWkTpWvHX6YJqB7BNyz6kNE1EUDuBjW"
wallet_address = "GeEnf1LpL2qrCW8o8FWyJsSZiCVCVh4TFk6evc7vky5z"

# AI API Keys
[ai_models]
gemini_api_key = "AIzaSyBxSGkxpIcrCfAplSbasWK7eEfbbPcgJeg"  # Gemini (Google) API

# Business Platform APIs
[make]
api_key = "726acbb9-1b9f-4c78-a72f-e3ca0e0129c4"
webhook_url = "https://hook.make.com/brotherhood-empire"

[gohighlevel]
api_url = "https://api.gohighlevel.com/v1/"
api_key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJsb2NhdGlvbl9pZCI6InVOeWRTOFJPZlJDTVoxY1c4aW1zIiwidmVyc2lvbiI6MSwiaWF0IjoxNzI3NjQ0OTcyMjU0LCJzdWIiOiJqNlhJSzN5RzdpOU40bXVBWGhNMSJ9.P8ClaucpuePeUT7DGXVm3psmnHjOr1n1SVObXmBdEcg"
location_id = "uNydS8ROfRCMZ1cW8ims"

# Automation Tools
[automation]
skyvern_api_key = "your_skyvern_api_key_here"
openadapt_config_path = "./config/openadapt"
openadapt_recording_dir = "./recordings"
skyvern_browser_path = "./browser"

# Communication
[telegram]
bot_token = "7838814763:AAGVkweVaww77zuWb6lUz4Fg6Xm5yiiEido"
webhook_url = "https://brotherhood-empire.netlify.app/.netlify/functions/telegram_webhook"

# DeFi Protocol Settings
[dex_programs]
raydium_program_id = "675kPX9MHTjS2zt1qfr1NYHuzeLXfQM9H24wFSUt1Mp8"
orca_program_id = "9W959DqEETiGZocYWCQPaJ6sBmUzgfxXfqGeTEdp3aQP"
serum_program_id = "9xQeWvG816bUx9EPjHmaT23yvVM2ZWbrrpZb9PusVFin"

[divine_settings]
min_liquidity = 50
min_volume = 10
max_slippage = 0.02
divine_blessing_threshold = 0.6
max_sol_per_trade = 0.1
stop_loss_percentage = 10
take_profit_percentage = 50
max_daily_trades = 5
risk_threshold = 0.2

# System Configuration
[system]
max_agents = 1000000
resource_allocation_strategy = "dynamic"
log_level = "info"
node_env = "development"

# Security
[security]
encryption_key = "fK9#mP2$vL5@nR8*qH3&jX6%cY4^wE7"
jwt_secret = "tB7#nM4$pQ9@kR5*hW2&vX8%cL6^yD3"
api_key = "zS5#jN8$mH4@vR6*wK9&cX2%pL7^tY3"

# API Keys
GOOGLE_API_KEY = "AIzaSyBxSGkxpIcrCfAplSbasWK7eEfbbPcgJeg"

# Stripe Configuration
STRIPE_SECRET_KEY = "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"
STRIPE_PUBLISHABLE_KEY = "pk_live_51QNQF2JX8wdxTT0olPAvGV02cnkmXkLMSXlb1MQEdGS93CQK7NdLRkOj2RjpV1K5pPAMMd6EpNSg6U7lzwC7gONb00sI3uPSGY"

# Database
DATABASE_URL = ""