name: Deploy to Cloud Services

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: |
          npm install
          pip install -r requirements.txt

      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v1.2
        with:
          publish-dir: './public'
          production-branch: main
          deploy-message: "Deploy from GitHub Actions"
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}

      - name: Update Telegram Webhook
        run: |
          curl -F "url=${{ secrets.TELEGRAM_WEBHOOK_URL }}" \
               https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/setWebhook

      - name: Configure Make.com Webhook
        run: |
          curl -X POST \
               -H "Authorization: Token ${{ secrets.MAKE_API_KEY }}" \
               -H "Content-Type: application/json" \
               -d '{"webhook_url": "${{ secrets.MAKE_WEBHOOK_URL }}"}' \
               ${{ secrets.MAKE_API_ENDPOINT }}

      - name: Deploy to DreamHost
        run: |
          curl -X POST \
               -H "Content-Type: application/json" \
               -d '{"key": "${{ secrets.DREAMHOST_API_KEY }}"}' \
               ${{ secrets.DREAMHOST_API_ENDPOINT }}
