name: Deploy to Cloud Services

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: |
          npm install
          pip install -r requirements.txt

      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v1.2
        with:
          publish-dir: './public'
          production-branch: main
          deploy-message: "Deploy from GitHub Actions"
          enable-pull-request-comment: true
          enable-commit-comment: true
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          TELEGRAM_BOT_TOKEN: "7838814763:AAGVkweVaww77zuWb6lUz4Fg6Xm5yiiEido"

      - name: Update Telegram Webhook
        run: |
          curl -F "url=https://brotherhood-empire.netlify.app/.netlify/functions/telegram_webhook" \
               https://api.telegram.org/bot7838814763:AAGVkweVaww77zuWb6lUz4Fg6Xm5yiiEido/setWebhook

      - name: Configure Make.com Webhook
        run: |
          curl -X POST \
               -H "Authorization: Token ${{ secrets.MAKE_API_KEY }}" \
               -H "Content-Type: application/json" \
               -d '{"webhook_url": "https://hook.make.com/brotherhood-empire"}' \
               https://hook.make.com/api/v2/webhooks

      - name: Deploy to DreamHost
        run: |
          python ghl-automation/dreamhost_manager.py --deploy
